{% set name = "tabulous" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tabulous-{{ version }}.tar.gz
  sha256: f2d32d55fad5b7013d431a4836cd3d55f7b7300a1af65f00fec71538e1a1785d

build:
  entry_points:
    - tabulous=tabulous.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - appdirs >=1.4.4
    - collections-undo >=0.0.7
    - magicgui >=0.5.1
    - matplotlib-base >=3.1
    - pandas >=1.5.2
    - psygnal >=0.9.0
    - python >=3.8
    - qt-command-palette >=0.0.6
    - qtconsole
    - qtpy >=1.10.0
    - requests
    - scikit-learn >=1
    - scipy >=1.7
    - seaborn >=0.11
    - tabulate
    - toml

test:
  imports:
    - tabulous
  commands:
    - pip list
    - pip check
    - tabulous --help
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/tabulous
  summary: A table data viewer for Python
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/hanjinliu/tabulous

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinliu
